### ISSUE TITLE
Port tests for `pystiche.loss.functional`

### ISSUE THREAD

**Issue by pmeier** [pystiche/pystiche#514]
In #500 the file `tests/integration/ops/test_functional.py` was missed to be ported to `tests/integration/loss/test_functional.py`

**Comment by sakshi-06** [comment]
Hi, @pmeier - Thanks for the awesome work on psytiche.

I wanted to work on this and subsequently work on the test suite cleanup. I have tested these changes on my local system, but the packages are broken on my system - so it might take one more day to push the changes as a part of a PR. I wished to ask if I could work on this issue if that's okay with you.

Thanks again!

**Comment by pmeier** [comment]
Hey @sakshi-06 that is awesome news! Please go ahead and work on it!

> I have tested these changes on my local system, but the packages are broken on my system

Can you give me a little more detail so I can help you? What is broken or not working?
