### ISSUE TITLE
Use `tqdm` in beginner example without `pystiche`

### ISSUE THREAD

**Issue by pmeier** [pystiche/pystiche#546]
Since  we use `tqdm` for our logging in `pystiche`, we should also use it in comparison example without `pystiche`:

https://github.com/pystiche/pystiche/blob/4fb1f7e425fd195b35284d7cbf7cd90b84be4333/examples/beginner/example_nst_without_pystiche.py#L446-L470

**Comment by DevPranjal** [comment]
Hi again @pmeier, I would like to submit a PR to fix this.

**Comment by pmeier** [comment]
Awesome, go ahead!
