### ISSUE TITLE
remove subtests from test suite

### ISSUE THREAD

**Issue by pmeier** [pystiche/pystiche#571]
Using the `unittest.TestCase.subTest` context manager was the usual way to run a test against multiple parametrizations or to separate multiple smaller tests. This has multiple disadvantages, from which not being able to run a single subtest is the most severe. Lately, we also discovered, that using a decorator that suppresses certain warnings in tests, also does not work with subtests (#566, cc @krshrimali).

Thus, we should start to remove it. For multiple parametrizations, we can simply replace it with [`pytest.mark.parametrize`](). If we have cases for multiple subtests in one test, we should either "inline" them or break up the test into multiple small ones.

I found references to the `subtest` fixture in the following folders:

- [x] `download` #575
- [x] `download/hub` #575
- [x] `integration` #574
- [x] `integration/data` #572
- [x] `integration/enc/models` #577
- [x] `integration/image` #578
- [x] `integration/loss` #579
- [x] `integration/ops` #580
- [x] `integration/pyramid` #576

Let's go folder by folder :slightly_smiling_face:

**Comment by ankitaS11** [comment]
Hi, @pmeier - got to know about this opened issue from @krshrimali. I was thinking to pick these up, confirming if that's okay?

**Comment by pmeier** [comment]
Hey @ankitaS11, always a pleasure to have new contributors. Welcome! Yes, pick anything from the list and get started. I've linked one that I've. You can use it as inspiration.

Leave the tests directly in the `integration` folder up to me. They are a little tricky.

**Comment by pmeier** [comment]
Hey @ankitaS11 any update on this? I want to move forward with #566 and this needs to be fixed first.
